### ISSUE TITLE
Minification is not working for me

### ISSUE THREAD

**Issue by heliohead** [kaiinui/middleman-inliner#1]
Hi,  @kaiinui,

Your gem is exactly what i need!, great job.

Are there  another configuration i need to do  except what is on readme?
For me is not working minification when build middleman,
I create a [repo test](https://github.com/heliohead/middleman-inline-css/blob/master/build/index.html) for that.

Thanx.

**Comment by kaiinui** [comment]
Hi, @heliohead,

Rename your `all.css` to `all.css.scss` (at `/source/stylesheets`) works!

Because `middleman-inliner` relies its css minification on compass, when you use `.css` it won't minify css.
This is of course wrong behavior. I will fix it.
For quick fix, please rename your stylesheets.

Thank you for reporting the issue.

**Comment by heliohead** [comment]
Thank you, @kaiinui,

It's work fine
